name: refine
channels:
  - pytorch
  - pytorch3d
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.8
  - pytorch3d=0.5.0
  - plyfile=0.7.4
  - pandas=1.3
  - cudatoolkit=11.1
  - gin-config
  - colored-traceback
  - tqdm
  - imageio
  - tensorboard=2.6
  - scipy
  - fastcore
  - joblib
  - transforms3d
  - matplotlib
  - pytorch-scatter
  - pip
  - pip:
    - git+https://github.com/princeton-vl/lietorch.git
    - opencv-python
    - wget
    - pypng
